Lobby
bpetetot/pongmmo pull request #49
Opened 2017-01-11 16:09 UTC by bpetetot

#42 finalize lobby screen

2017-01-11 16:11 UTC, bpetetot commented
@fabienjuif @frinyvonnick what do you think about this lobby architecture and gui components ?

2017-01-12 11:35 UTC, fabienjuif requested changes
First review

2017-01-12 11:35 UTC, fabienjuif commented on package.json
> +      "no-underscore-dangle": 0,
I prefer to let this activated

2017-01-12 11:35 UTC, fabienjuif commented on src/gui/components/Button.js
> +export const DEFAULT_OPTIONS = {
Why do you export `DEFAULT_OPTIONS` in all components ?
How do you think about a static property (like react do) on the class ?

2017-01-12 11:35 UTC, fabienjuif commented
Seems pretty cool overall :)

2017-01-16 14:00 UTC, bpetetot commented
This PR starts to be very big, can you do a review to merge it... then I will make smaller PR

2017-01-16 14:07 UTC, fabienjuif approved these changes
When I see all the code to do a simple UI I ask myself if this is not worth it to have an UI lib eventually.

2017-01-16 14:19 UTC, bpetetot commented
I agree but I searched for UI libs with pixi.js and nothing seems stable.....

2017-01-16 14:24 UTC, frinyvonnick commented on src/gui/renderer/entities/walls.js
> +import { convert } from '../../../utils'
Could we configure webpack to import from root ?

2017-01-16 14:24 UTC, frinyvonnick approved these changes

2017-01-16 14:24 UTC, fabienjuif commented on src/gui/renderer/entities/walls.js
> +import { convert } from '../../../utils'
The issue is on you :p https://github.com/bpetetot/pongmmo/issues/21

2017-01-16 14:26 UTC, bpetetot commented on src/gui/renderer/entities/walls.js
> +import { convert } from '../../../utils'
Already identified : #21

2017-01-16 14:26 UTC, merged